//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using CoffeeShop.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon : BaseViewModel
    {
        public HoaDon()
        {
            this.ChiTietHoaDon = new HashSet<ChiTietHoaDon>();
        }

        #region private variables
        private int _ma;
        private System.DateTime _ngayTao;
        private Nullable<int> _maKH;
        private Nullable<int> _diemTichLuy;
        private int _tongTien;

        #endregion

        #region properties
        public int Ma { get => _ma; set { _ma = value; OnPropertyChanged(); } }
        public System.DateTime NgayTao { get => _ngayTao; set { _ngayTao = value; OnPropertyChanged(); } }
        public Nullable<int> MaKH { get => _maKH; set { _maKH = value; OnPropertyChanged(); } }
        public Nullable<int> DiemTichLuy { get => _diemTichLuy; set { _diemTichLuy = value; OnPropertyChanged(); } }
        public int TongTien { get => _tongTien; set { _tongTien = value; OnPropertyChanged(); } }

        #endregion

        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDon { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
