//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using CoffeeShop.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class KhoNguyenLieu : BaseViewModel
    {
        public KhoNguyenLieu()
        {
            this.NguyenLieu = new HashSet<NguyenLieu>();
        }

        #region private variables
        private int _maNL;
        private string _ten;
        private int _soLuong;
        private string _donVi;

        #endregion

        #region properties
        public int MaNL { get => _maNL; set { _maNL = value; OnPropertyChanged(); } }
        public string Ten { get => _ten; set { _ten = value; OnPropertyChanged(); } }
        public int SoLuong { get => _soLuong; set { _soLuong = value; OnPropertyChanged(); } }
        public string DonVi { get => _donVi; set { _donVi = value; OnPropertyChanged(); } }

        #endregion

        public virtual ICollection<NguyenLieu> NguyenLieu { get; set; }
    }
}
