//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using CoffeeShop.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiSanPham : BaseViewModel
    {
        public LoaiSanPham()
        {
            this.SanPham = new HashSet<SanPham>();
        }

        #region private variables
        private int _ma;
        private string _ten;

        #endregion

        #region properties
        public int Ma { get => _ma; set { _ma = value; OnPropertyChanged(); } }
        public string Ten { get => _ten; set { _ten = value; OnPropertyChanged(); } }

        #endregion

        public virtual ICollection<SanPham> SanPham { get; set; }
    }
}
