//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using CoffeeShop.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham : BaseViewModel
    {
        public SanPham()
        {
            this.NguyenLieu = new HashSet<NguyenLieu>();
        }

        #region private variables
        private int _ma ;
        private string _ten ;
        private int _maLoai ;
        private int _gia ;
        private string _anh ;

        #endregion

        #region properties
        public int Ma { get => _ma; set { _ma = value; OnPropertyChanged(); } }
        public string Ten { get => _ten; set { _ten = value; OnPropertyChanged(); } }
        public int MaLoai { get => _maLoai; set { _maLoai = value; OnPropertyChanged(); } }
        public int Gia { get => _gia; set { _gia = value; OnPropertyChanged(); } }
        public string Anh { get => _anh; set { _anh = value; OnPropertyChanged(); } }

        #endregion

        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual ICollection<NguyenLieu> NguyenLieu { get; set; }
    }
}
